// HERE WE CAN CUSTOMIZE OUR LAYOUTPROVIDER COMPONENT
// WHICH CAN BE SHARED ACROSS THE ENTIRE LIKE NAVBAR, MENUITEMS, FOOTER ETC
// IT ACTS AS A WRAPPER FOR THE layout.tsx GENERATED BY NEXT.JS

export default function LayoutProvider({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
