import LayoutProvider from "@/components/LayoutProvider";
import "./globals.css";

export const metadata = {
  title: "NEXT BUDECOMM",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <LayoutProvider>
      <body>{children}</body>
    </LayoutProvider>
  );
}
